---
title: "202503_TCRseq_reanalysis"
output: html_document
date: "2025-03-27"
---

#Updated code for scTCR analysis based on reviewer #1 comment regarding including all samples from Roider et al 2024
#Information about these samples can be found in STable1 in the original publication
```{r}
library(Seurat)
library(dplyr)
library(purrr)
library(data.table)
library(ggplot2)
library(ggrastr)
library(ggpubr)
```

```{r}
colors_umap_cl <- 
  c("1"=brewer.pal(9, "Purples")[4],
    "2"=brewer.pal(9, "Purples")[6],
    "3"=brewer.pal(9, "YlOrRd")[4],
    #"4"=brewer.pal(9, "YlOrRd")[8],
    "5"=brewer.pal(9, "YlOrRd")[7],
    "6"=brewer.pal(9, "Greens")[6],
    "8"=brewer.pal(9, "Blues")[3],
    "9"=brewer.pal(9, "Purples")[8],
    #"10"=brewer.pal(9, "YlOrRd")[5],
    "11"=brewer.pal(9, "Blues")[9],
    "12"=brewer.pal(9, "YlOrRd")[3],
    "13"=brewer.pal(9, "Blues")[5],
    "14"=brewer.pal(9, "RdPu")[7],
    "15"=brewer.pal(9, "Blues")[7],
    "16"=brewer.pal(9, "YlOrRd")[6],
    "18"=brewer.pal(9, "YlOrRd")[9],
    "19"=brewer.pal(9, "Greys")[4]
  )

mytheme_1 <- theme_bw()+
  theme(axis.title = element_text(size=10, color="black"),
        axis.text = element_text(size=10, color="black"),
        legend.position = "none",
        legend.text = element_text(size = 8, color="black"),
        legend.title = element_text(size = 10, color="black"),
        legend.key.width = unit(0.5, "cm"),
        plot.title = element_text(hjust = 0.5, size = 10, color="black", face = "bold"),
        panel.border = element_rect(size=0.25),
        strip.background = element_rect(fill="white", size=0.5),
        strip.text = element_text(size=6.5, color="black"),
        panel.grid = element_blank()
        )
```


```{r}
SeuratProc_T <- function(sobj, verbose=FALSE, dims.clustering=NULL, resolution.clustering=NULL, dims.umap=NULL) {
  sobj <- DietSeurat(sobj)
  DefaultAssay(sobj) <- "RNA"
  sobj <- FindVariableFeatures(sobj, selection.method = "vst", nfeatures = 2000, verbose=verbose)
  sobj <- ScaleData(sobj, features = rownames(sobj), verbose=verbose)
  sobj <- CellCycleScoring(sobj, s.features = cc.genes$s.genes, g2m.features = cc.genes$g2m.genes, set.ident = TRUE)
  sobj <- ScaleData(sobj, vars.to.regress = c("S.Score", "G2M.Score", "percent.mt"), verbose=verbose)
  sobj <- RunPCA(sobj, features = VariableFeatures(sobj), reduction.name = "pcaRNA", reduction.key = "pcaRNA_")
  sobj <- FindNeighbors(sobj, dims = dims.clustering, verbose=verbose, reduction = "pcaRNA")
  sobj <- FindClusters(sobj, resolution = resolution.clustering, verbose=verbose)
  sobj <- RunUMAP(sobj, dims = dims.umap, verbose=verbose, reduction.key = "umapRNA_", reduction.name = "umapRNA", reduction = "pcaRNA")
  return(sobj)
}
```

```{r}
sample_list <- c("LN0132", "LN0144", "LN0178", "LN0193", "LN0198", 
                 "LN0243", "LN0249", "LN0259", "LN0264", "LN0278", "LN0417")

dir_path <- "/omics/groups/OE0606/internal/amathiou/Projects/202402_PhDpapers/LNStroma/202503_TCRseq/"
contig_path <- file.path(dir_path, "contig_files")

Combined_T <- readRDS(file.path(dir_path, "Tcells_Integrated.rds"))
```

```{r}
sobjs_T <- lapply(sample_list, 
                  function(sample_id) {
  print(paste0('Reading in sample: ', sample_id))
  file <- file.path(dir_path, paste0('SeuratObjectProc_', sample_id, ".rds"))
  sobj <- readRDS(file)
  sobj$PatientID <- sample_id
  sobj[["percent.mt"]] <- PercentageFeatureSet(sobj, pattern = "^MT-")
  sobj <- NormalizeData(sobj)
  sobj <- SeuratProc_T(sobj, 
                       verbose=FALSE, 
                       dims.clustering=1:14, 
                       resolution.clustering=0.4, 
                       dims.umap=1:13)
  return(sobj)
})
names(sobjs_T) <- sample_list
saveRDS(sobjs_T, file.path(dir_path, "sobjs_Tmapped.rds"))
```

```{r}
sobjs_T_mapped <- lapply(sobjs_T, function(sobj) {
  anchors <- FindTransferAnchors(reference = Combined_T, query = sobj, reference.reduction = "pcaRNA")
  sobj <- MapQuery(anchorset = anchors, reference = Combined_T, query = sobj,
                   reduction.model = "wnn.umap",
                   refdata = list(predicted.celltype = "IdentI"),
                   reference.reduction = "pcaRNA")
  return(sobj)
})
names(sobjs_T_mapped) <- sample_list

saveRDS(sobjs_T_mapped, file.path(dir_path, "sobjs_Tmapped_2.rds"))
```

```{r}
readTCR <- function(files=NULL){
  lapply(files, fread) %>% 
    bind_rows() %>% 
    as_tibble() %>% 
    mutate(PatientID = sapply(strsplit(barcode, "_"), `[`, 2)) %>% 
    rename(Barcode_full = barcode)
}

tcr_files <- list.files(path = contig_path, pattern = "^filtered_contig_annotations_new_.*\\.csv$", full.names = TRUE) #From Roider et al 2024
DF_TCRrep <- readTCR(tcr_files)
```

```{r}
merged_meta <- map2_dfr(names(sobjs_T_mapped), sobjs_T_mapped, function(name, obj) {
  data.frame(Barcode_full = rownames(obj@meta.data),
             PatientID = name,
             predicted.celltype = obj$predicted.predicted.celltype,
             stringsAsFactors = FALSE)
})

merged_umap <- map2_dfr(names(sobjs_T_mapped), sobjs_T_mapped, function(name, obj) {
  umap <- obj@reductions$ref.umap@cell.embeddings
  umap_df <- as.data.frame(umap)
  umap_df$Barcode_full <- rownames(umap)
  umap_df
})

combined_meta <- merge(merged_meta, merged_umap, by = "Barcode_full")

DF_TCRrep <- merge(DF_TCRrep, combined_meta, by = "Barcode_full")

#Patient annotation
entity_map <- tibble::tibble(
  PatientID = c("LN0132", "LN0144", "LN0178", "LN0193", "LN0198", 
                "LN0243", "LN0249", "LN0259", "LN0264", "LN0278", "LN0417"),
  Entity = c("rLN", "FL", "DLBCL", "DLBCL", "FL",
             "FL", "FL", "rLN", "rLN", "FL", "DLBCL")
)
```

```{r}
DF_TCRrep <- DF_TCRrep %>% 
  left_join(entity_map, by = "PatientID")
```

```{r}
df_clonotypes <- DF_TCRrep %>% 
  filter(!is.na(raw_clonotype_id), !is.na(Entity)) %>% 
  select(Barcode_full, PatientID, raw_clonotype_id, refUMAP_1, refUMAP_2, predicted.celltype, Entity) %>% 
  distinct() %>% 
  add_count(PatientID, raw_clonotype_id, predicted.celltype) %>% 
  group_by(PatientID, raw_clonotype_id, predicted.celltype) %>% 
  summarise(refUMAP_1 = median(refUMAP_1),
            refUMAP_2 = median(refUMAP_2),
            n = first(n),
            Entity = first(Entity),
            .groups = "drop") %>% 
  mutate(n = ifelse(n > 50, 50, n)) %>% 
  filter(predicted.celltype %in% c(3, 5, 16)) # CD8 EM types
```

```{r}
DF_5prime_umap <- DF_TCRrep %>% 
  filter(!is.na(Entity)) %>%
  dplyr::select(refUMAP_1, refUMAP_2, predicted.celltype, Entity, PatientID.x) %>% 
  distinct() %>% 
  mutate(Entity=factor(Entity, levels=c("rLN", "FL", "DLBCL")))

DF_5prime_umap_cd8 <- DF_5prime_umap[which(DF_5prime_umap$predicted.celltype %in% c(3, 5, 16)), ]
```

```{r}
#Annotations not provided in the object, had to select based on Figure 1 in Roider et al 2024
DefaultAssay(Combined_T) <- 'RNA'
DimPlot(Combined_T, label = T, reduction = 'wnn.umap')
```

```{r}
DF_TCRrep_cd8 <- DF_TCRrep[which(DF_TCRrep$predicted.celltype %in% c(3, 5, 16)), ]#Annotations not provided in the object, had to select based on Figure 1 in Roider et al 2024
clonotype_df <- as.data.frame.matrix(table(DF_TCRrep_cd8$raw_clonotype_id, DF_TCRrep_cd8$Entity))
clonotype_freq <- as.data.frame(rowSums(clonotype_df))
colnames(clonotype_freq) <- "Freq"

pdf("/omics/groups/OE0606/internal/amathiou/Projects/202402_PhDpapers/LNStroma/202503_TCRseq/SFig10_panelA_clonesize.pdf", width = 6, height = 4)
ggplot(clonotype_freq, aes(x = log10(Freq) )) + 
  geom_density() + 
  theme_bw() + 
  geom_vline(xintercept = log10(6), 
             linetype="dashed", color = "#7F0000", size=1) +
  xlab("log10(Freq_Clone)") + 
  ggtitle("4,220 clonotypes")
dev.off()
```

```{r}
#From seurat object extract cxcl13 and ifng expression
df <- data.frame()
df <- lapply(names(sobjs_T_mapped), function(sample){
  as.data.frame(t(as.data.frame(sobjs_T_mapped[[sample]]@assays$RNA@data)[c("IFNG", "CXCL13", "CCR7", "CXCR3"), ]))
})
merged_exp <- df %>% map_df(bind_rows)
merged_exp$Barcode_full <- rownames(merged_exp)
DF_TCRrep_cd8 <- merge(DF_TCRrep_cd8, merged_exp, by = "Barcode_full")

df_clonotypes <- 
  DF_TCRrep_cd8 %>% 
  filter(!is.na(raw_clonotype_id)) %>% 
  filter(!is.na(Entity)) %>% 
  mutate(Entity=factor(Entity, levels=c("rLN", "FL", "DLBCL")))
```

```{r}
clone_df <- data.frame(Clone = unique(df_clonotypes$raw_clonotype_id))
clone_df$IFNG <- unlist(lapply(unique(df_clonotypes$raw_clonotype_id), function(clonotype){
  mean(df_clonotypes[which(df_clonotypes$raw_clonotype_id == clonotype), "IFNG"])
  }))

clone_df$Freq <- unlist(lapply(unique(df_clonotypes$raw_clonotype_id), 
                               function(clonotype){
  nrow(df_clonotypes[which(df_clonotypes$raw_clonotype_id == clonotype), ])
  }))

clone_df$Expanded <- ifelse(clone_df$Freq > 6, 
                            "Expanded", 
                            "Non-expanded")
pdf("/omics/groups/OE0606/internal/amathiou/Projects/202402_PhDpapers/LNStroma/202503_TCRseq/SFig10_panelB_clonesize_ifng_correlation.pdf", width = 6, height = 4)

ggplot(clone_df, aes(x = log10(Freq), y = IFNG, color = Expanded, fill = Expanded)) + 
  geom_point() + 
  theme_bw() + 
  ggtitle("CD8+ T cells") + 
  xlab("log10(Clone Size)") + 
  geom_smooth(method = "lm", se = TRUE, fullrange = F) + 
  scale_color_manual(values = c("#7F0000", "darkgrey")) + 
  scale_fill_manual(values = c("#7F0000", "darkgrey"))
dev.off()
```

```{r}
clone_df <- data.frame(Clone = unique(df_clonotypes$raw_clonotype_id))

# Mean IFNG expression per clone
clone_df$IFNG <- unlist(lapply(clone_df$Clone, function(clonotype) {
  mean(df_clonotypes[df_clonotypes$raw_clonotype_id == clonotype, "IFNG"])
}))

# Mean CXCL13 expression per clone
clone_df$CXCL13 <- unlist(lapply(clone_df$Clone, function(clonotype) {
  mean(df_clonotypes[df_clonotypes$raw_clonotype_id == clonotype, "CXCL13"])
}))

# Clone size (frequency)
clone_df$Freq <- unlist(lapply(clone_df$Clone, function(clonotype) {
  nrow(df_clonotypes[df_clonotypes$raw_clonotype_id == clonotype, ])
}))

# Expansion status
clone_df$Expanded <- ifelse(clone_df$Freq > 6, "Expanded", "Non-expanded")

pdf("/omics/groups/OE0606/internal/amathiou/Projects/202402_PhDpapers/LNStroma/202503_TCRseq/response_letter_cxcl13_ifng_correlation.pdf", width = 6, height = 4)
ggplot(clone_df, aes(x = CXCL13, y = IFNG, color = Expanded)) + 
  geom_point(size = 1) + 
  geom_smooth(data = clone_df_corr, aes(x = CXCL13, y = IFNG), 
              method = "lm", se = TRUE, color = "black", inherit.aes = FALSE) +
  scale_color_manual(values = c("Expanded" = "#7F0000", "Non-expanded" = "darkgrey")) +
  theme_bw() + 
  ggtitle("CXCL13 vs IFNG (per clone)") + 
  xlab("Mean CXCL13 expression (per clone)") + 
  ylab("Mean IFNG expression (per clone)")
dev.off()
```

```{r, Stats on gene expression}
# Total number of unique clones
n_clones_total <- nrow(clone_df)

# Clones expressing CXCL13, IFNG, or both
n_clones_cxcl13 <- sum(clone_df$CXCL13 > 0)
n_clones_ifng <- sum(clone_df$IFNG > 0)
n_clones_both <- sum(clone_df$CXCL13 > 0 & clone_df$IFNG > 0)
n_clones_either <- sum(clone_df$CXCL13 == 0 & clone_df$IFNG == 0)

# Print results
cat("Total clonotypes:", n_clones_total, "\n")
cat("Fraction of clonotypes expressing CXCL13:", round(n_clones_cxcl13 / n_clones_total, 3), "\n")
cat("Fraction of clonotypes expressing IFNG:", round(n_clones_ifng / n_clones_total, 3), "\n")
cat("Fraction of clonotypes expressing BOTH CXCL13 & IFNG:", round(n_clones_both / n_clones_total, 3), "\n")
cat("Fraction of clonotypes expressing EITHER CXCL13 or IFNG:", round(n_clones_either / n_clones_total, 3), "\n")

```

```{r}
clone_df <- data.frame(Clone = unique(df_clonotypes$raw_clonotype_id))
clone_df$IFNG <- unlist(lapply(unique(df_clonotypes$raw_clonotype_id), 
                               function(clonotype){
                                 mean(df_clonotypes[which(df_clonotypes$raw_clonotype_id == clonotype), "IFNG"])
                                 }))

clone_df$Freq <- unlist(lapply(unique(df_clonotypes$raw_clonotype_id), 
                               function(clonotype){
                                 nrow(df_clonotypes[which(df_clonotypes$raw_clonotype_id == clonotype), ])
                                 }))
```

```{r}
clone_df$Expanded <- ifelse(clone_df$Freq > 6, "Yes", "No")

clones_meta <- clone_df[, c("Clone", "Expanded")]
colnames(clones_meta) <- c("raw_clonotype_id", "Expanded")

df_clonotypes <- merge(df_clonotypes, 
                       clones_meta, by = "raw_clonotype_id")

clone_entity_bar <- as.data.frame(table(df_clonotypes$Expanded, df_clonotypes$Entity))
colnames(clone_entity_bar) <- c("Expanded", "Entity", "Freq")
```

```{r}
pdf("/omics/groups/OE0606/internal/amathiou/Projects/202402_PhDpapers/LNStroma/202503_TCRseq/Figure3_G_ifng_clonal.pdf", width = 7, height = 3)
ggplot(df_clonotypes, aes(x = Expanded, y = IFNG)) + 
  geom_boxplot(aes(color = Expanded, fill = Expanded), alpha = 0.5, outlier.size = 0.05) + 
  theme_bw() + 
  facet_wrap(~Entity) + 
  scale_color_manual(values = c("darkgrey", "#7F0000")) + 
  scale_fill_manual(values = c("lightgrey", "#B13A2C")) + stat_compare_means()
dev.off()

pdf("/g/scb2/zaugg/amathiou/2021July_LNS012/10.TCRseq/Figure3_G_Barplot_alternative.pdf", width = 3, height = 3)
ggplot(clone_entity_bar %>% mutate(Entity=factor(Entity, levels=rev(c("rLN", "FL", "DLBCL")))), 
       aes(x = Expanded, y = Freq, fill = Entity, label=Freq)) + 
  geom_bar(stat = "identity", position = "fill") + 
  theme_classic() + 
  scale_fill_manual(values = c("#67B86E", "#8BCDE0", "#8D60B5"))
dev.off()

pdf("/g/scb2/zaugg/amathiou/2021July_LNS012/10.TCRseq/Figure3_G_Barplot.pdf", width = 3, height = 3)
ggplot(clone_entity_bar %>% mutate(Entity=factor(Entity, levels=c("rLN", "FL", "DLBCL"))), 
       aes(y = Freq, x = Entity, label=Freq, color = Expanded, fill = Expanded)) + 
  geom_bar(stat = "identity", position = "fill", alpha = 0.5) + 
  scale_color_manual(values = c("darkgrey", "#7F0000")) + 
  scale_fill_manual(values = c("lightgrey", "#B13A2C")) + 
  theme_classic()
dev.off()
```

