##Figure colors

annotation_colors <- list("patient"= c("DLBCL-1"="#33691E",
                                       "DLBCL-2"="#55882f",
                                       "DLBCL-3"="#689F38",
                                       "DLBCL-4"="#7CB342",
                                       "DLBCL-5"="#8BC34A",
                                       "DLBCL-6"="#9CCC65",
                                       "DLBCL-7"="#AED581",
                                       "DLBCL-8"="#C5E1A5",
                                       "FL-1"="#86B0D3",
                                       "FL-2"="#5D9FC9",
                                       "FL-3"="#318DBE",
                                       "FL-4"="#0D75B2",
                                       "FL-5"="#04649C",
                                       "FL-6"="#03507E",
                                       "rLN-1"="#40004B",
                                       "rLN-2"="#71267D",
                                       "rLN-3"="#9263A3",
                                       "rLN-4"="#B696C5",
                                       "rLN-5"="#D9C2DE"),
                          "Type_binned"= c("rLN"= "#8D60B5",
                                           "FL"= "#8BCDE0",
                                           "DLBCL"= "#67B86E"),
                          "Type_binned_v2"=c("Healthy"= "#8D60B5",
                                             "FL"= "#8BCDE0",
                                             "DLBCL"= "#67B86E"),
                          "Type_binned_v3"=c("Tonsil"= "#8D60B5",
                                             "FL"= "#8BCDE0",
                                             "DLBCL"= "#67B86E"),
                          "Type_binned_v4"=c("Tonsil"= "#8D60B5",
                                             "FL"= "#8BCDE0",
                                             "FL/DLBCL"= "#009C9E",
                                             "DLBCL"= "#67B86E"),
                          "Clusters_final"=c("artBEC"="#F31515",
                                             "bLEC"="#C2A946",
                                             "capBEC"="#F5818D",
                                             "cLEC"="#FF9709",
                                             "collectLEC"="#FFF16A",
                                             "DLBCL-B"="#83CAE8",
                                             "FDC"="#088B1A",
                                             "FL-B"="#0EBCE8",
                                             "fLEC"="gold1",
                                             "Healthy B"="#0C80ED",
                                             "MRC/IFR"="#A1D74F",
                                             "LAF"="#2AC200",
                                             "med-FRC"="#005C4C",
                                             "msLEC"="#F5C56C",
                                             "Myeloid"="snow3",
                                             "PC"="#0330E3",
                                             "PvC"="#659445",
                                             "SMC"="#4E7329", #"#BEDEA6",
                                             "T-FH"="mediumorchid1",
                                             "T-H"="magenta4",
                                             "T-PR"="purple4",
                                             "T-REG"="darkorchid1",
                                             "T-TOX"="mediumpurple1",
                                             "TRC"="#96B577",
                                             "tipBEC"="hotpink1", 
                                             "LA-BEC"="hotpink1",
                                             "valveLEC"="#9E770E",
                                             "vnBEC"="#9C194B"),
                          "Cluster_scribian"=c("B"="#0C80ED",
                                               "BEC"="#9C194B",
                                               "FDC"="#088B1A",
                                               "MSC"="#A1D74F",
                                               "LAF"="#2AC200",
                                               "T-FH"="mediumorchid1",
                                               "T-H"="magenta4",
                                               "T-PR"="purple4",
                                               "T-REG"="darkorchid1",
                                               "T-TOX"="mediumpurple1",
                                               "PvC"="#659445",
                                               "T-PR"="purple4",
                                               "Myeloid"="snow3",
                                               "LA-BEC"="hotpink1",
                                               "LEC"="#FF9709",
                                               "PC"="#0330E3"),
                          "features"=c(pals::parula(1000)),
                          "Clusters_paper"=c("artBEC"="#F31515",
                                             "bLEC"="#C2A946",
                                             "capBEC"="#F5818D",
                                             "cLEC"="#FF9709",
                                             "collectLEC"="#FFF16A",
                                             "DLBCL-B"="#83CAE8",
                                             "FL-B"="#0EBCE8",
                                             "fLEC"="gold1",
                                             "Healthy B"="#0C80ED",
                                             "B-FRC"="#A1D74F",
                                             "LAF"="#2AC200",
                                             "med-FRC"="#005C4C",
                                             "msLEC"="#F5C56C",
                                             "Myeloid"="snow3",
                                             "PC"="#0330E3",
                                             "T-FRC"="#96B577", #"#BEDEA6",
                                             "T-FH"="mediumorchid1",
                                             "T-H"="magenta4",
                                             "T-PR"="purple4",
                                             "T-REG"="darkorchid1",
                                             "T-TOX"="mediumpurple1",
                                             "LA-BEC"="hotpink1",
                                             "valveLEC"="#9E770E",
                                             "vnBEC"="#9C194B")
)




theme_figures <- theme_bw()+
  theme(
    plot.title = element_text(size = 13, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(color = "black"),
    aspect.ratio=1,
    legend.position="none",
    axis.text.y = element_text(size = 10, color = "black"),
    axis.text.x = element_text(size = 10, color = "black"),
    axis.title.x = element_text(size = 10, color = "black"),
    axis.title.y = element_text(size = 10, color = "black", vjust = 1))
#