---
title: "Figure4"
output: html_document
date: "2024-02-29"
---

---
title: "Figure 4"
output: html_document
---


# Load packages
```{r setup, include=FALSE}
library(Seurat)
library(data.table)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(readr)
library(tidyverse)
library(ggalluvial)
library(aws.s3)
```

# Load objects
```{r setup, include=FALSE}
# scRNA-seq
scRNA <- readRDS("") #Available in zenodo as "scRNA_LN_stromal_cells.rds"

# Scriabin data
interaction_potential <- readRDS("") #Available in zenodo as "interaction_potential.rds"
source("/path/to/Figure_config.R")
```

# Panels 
## B
The interaction potential was calculated as stated in https://github.com/BlishLab/scriabin/blob/main/vignettes/single-dataset.Rmd. As data base "Chemokines" from the CytoSig were used. The calculation was done per patient and merged into one object interaction_potential.rds.

```{r Panel B, fig.height=8, fig.width=8, fig.cap="UMAP interaction potential"}
DimPlot(interaction_potential, group.by = "zones", cols=c("orange2", "#368F8A", "grey70", "#C0C26D"))+
  scale_x_reverse()+scale_y_reverse()+theme_void()
```

## C
```{r Panel C, fig.height=6, fig.width=12, fig.cap="UMAP feature plot color coded by the geometic mean expression of chemokines"}}
FeaturePlots <- FeaturePlot(interaction_potential, features = c("CXCL12=CXCR4", "CXCL13=CXCR5","CCL19=CCR7","CCL21=CCR7",
                                     "CXCL9=CXCR3","CXCL10=CXCR3","CXCL11=CXCR3"), combine = F)

lapply(seq(1:7), function(i){
  FeaturePlots[[i]] + scale_colour_gradientn(colours = c("#ECECEC", "#AD2E24"))+theme_void()+scale_y_reverse()+scale_x_reverse()
})
```

## D
```{r}
data <- interaction_potential@meta.data %>%
  dplyr::select(zones, seurat_clusters, sender_new_v3, receiver_new_v3, sender_group) %>%
  group_by(zones, sender_group, sender_new_v3, receiver_new_v3) %>% tally()

p1 <- as.data.frame(data) %>% dplyr::filter(zones=="B cell zone like ngh") %>% dplyr::filter(sender_group=="rLN") %>% 
  mutate(q50 = quantile(n, 0.5)) %>% dplyr::filter(n>unique(q50)) %>% 
  ggplot(aes(y = n, axis1 = sender_new_v3, axis2 = receiver_new_v3)) +
  geom_alluvium(aes(fill = sender_new_v3), width = 1/12)+
  geom_stratum(width = 1/12, fill = "grey70", color = "black") +
  #geom_label(stat = "stratum", aes(label = after_stat(stratum)))+
  scale_fill_manual(values = annotation_colors$Clusters_paper)+
  ggrepel::geom_text_repel(
    aes(label = ifelse(after_stat(x) == 1, as.character(after_stat(stratum)), NA)),
    stat = "stratum", size = 3, direction = "y", nudge_x = -5
  )  +  ggrepel::geom_text_repel(
    aes(label = ifelse(after_stat(x) == 2, as.character(after_stat(stratum)), NA)),
    stat = "stratum", size = 3, direction = "y", nudge_x = +5
  )+theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        #legend.position = "bottom",
        panel.background = element_rect(colour = "grey60", size=0.5))+
  xlab("")+
  ylab("")

p3 <- as.data.frame(data) %>% dplyr::filter(zones=="T cell zone like ngh") %>% dplyr::filter(sender_group=="rLN") %>% 
    mutate(q50 = quantile(n, 0.50)) %>% dplyr::filter(n>unique(q50)) %>% 
  ggplot(aes(y = n, axis1 = sender_new_v3, axis2 = receiver_new_v3)) +
  geom_alluvium(aes(fill = sender_new_v3), width = 1/12)+
  geom_stratum(width = 1/12, fill = "grey70", color = "black") +
  #geom_label(stat = "stratum", aes(label = after_stat(stratum)))+
  scale_fill_manual(values = annotation_colors$Clusters_paper)+
  ggrepel::geom_text_repel(
    aes(label = ifelse(after_stat(x) == 1, as.character(after_stat(stratum)), NA)),
    stat = "stratum", size = 3, direction = "y", nudge_x = -5
  )  +  ggrepel::geom_text_repel(
    aes(label = ifelse(after_stat(x) == 2, as.character(after_stat(stratum)), NA)),
    stat = "stratum", size = 3, direction = "y", nudge_x = +5
  )+theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        #legend.position = "bottom",
        panel.background = element_rect(colour = "grey60", size=0.5))+
  xlab("")+
  ylab("")
```

## E
```{r}
k6Data_rLN <- read_csv("") #percent of total interactions in a KNN-based cell-cell interaction analysis (k=6) of rLN samples in the mIF dataset; available in zenodo as "mIF_knn_k6_pct_totalinteractions_rLN.csv"

k6Data_rLN$summary_zone <- k6Data_rLN$id_nhood.x
k6Data_rLN$summary_zone[k6Data_rLN$id_nhood.x %in% c("BEC-rich T zone", "T zone")] <- "T zone"
k6Data_rLN$summary_zone[k6Data_rLN$id_nhood.x %in% c("B prol niche", "Follicle cluster 1")] <- "B zone"


k6Data_rLN_summary <- k6Data_rLN %>% group_by(summary_zone, pair) %>% summarise(n_pair_summary= sum(n_pair), 
                                                                                n_total_summary = sum(n_total))
k6Data_rLN_summary$fraction <- k6Data_rLN_summary$n_pair_summary/k6Data_rLN_summary$n_total_summary
data <- k6Data_rLN_summary %>% 
    filter(pair %in% c("FDC_B", "T-FH_B", "MSC_B", "MSC_T-H", "MSC_T-TOX", "MSC_T-REG", "MSC_Myeloid")) %>%
    filter(summary_zone %in% c("T zone","B zone")) %>% 
    dplyr::select(summary_zone, pair, fraction) %>%  
    pivot_wider(values_from = fraction, names_from = pair) %>% column_to_rownames("summary_zone") %>% 
    #scale() %>% 
    t()

data_scriabin <- interaction_potential@meta.data %>% 
  group_by(sender_group, zones, sender_receiver_v3) %>% tally() %>% 
  ungroup() %>% group_by(zones) %>%  mutate(Frac = n/sum(n)) %>% 
  filter(sender_group=="rLN") %>% 
  filter(sender_receiver_v3 %in% c("FDC_B", "T-FH_B", "MSC_B", "MSC_T-H", "MSC_T-TOX", "MSC_T-REG", "MSC_Myeloid")) %>%
  filter(!zones %in% c("other")) %>% 
  dplyr::select(zones, sender_receiver_v3, Frac) %>%  
  pivot_wider(values_from = "Frac", names_from = sender_receiver_v3) %>% column_to_rownames("zones")


data_joined <- t(data_scriabin) %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  left_join(rownames_to_column(as.data.frame(data))) %>% 
  column_to_rownames()

#data_joined$`B cell zone like ngh`[5:6] <- 0.000001

data_joined <- t(data_joined[-2,])
data_joined <- data_joined[-2,]

row_order <- c("B zone", "B cell zone like ngh", "T zone", "T cell zone like ngh")
data_joined <- data_joined[c(row_order, setdiff(rownames(data_joined), row_order)), ]


col_order <-  c("MSC_T-REG","MSC_Myeloid","MSC_T-TOX", "MSC_T-H", "FDC_B")
data_joined <- data_joined[,c(col_order, setdiff(rownames(data_joined), row_order))]

col_fun <- circlize::colorRamp2(c(-1, 0, 1), c("#007EA7", "white", "#AD2E24"))
vals <- seq(-1, 1, length.out = 1000)
colors <- col_fun(vals) 
pheatmap::pheatmap(data_joined,  
          color = colors,
          #rev(colorspace::diverging_hcl(n = 40, h = c(-324, 193), c = 100, l = c(60, 100), power = 1)), 
          scale = "column", cluster_cols = F, cluster_rows = F, na_col = "grey80")+coord_flip() 
  

```


## F
```{r}
interaction_potential$UMAP_1 <- interaction_potential@reductions$umap@cell.embeddings[,1]
interaction_potential$UMAP_2 <- interaction_potential@reductions$umap@cell.embeddings[,2]
interaction_potential@meta.data %>%
  arrange(factor(sender_group, levels = c("FL","DLBCL","rLN"))) %>% ggplot() + 
  scattermore::geom_scattermore(mapping = aes_string(x = "UMAP_1", 
                                                     y = "UMAP_2", color = "sender_group"))+
  scale_color_manual(values = c("#8D60B5", "grey85","grey85"))+
  scale_x_reverse()+
  scale_y_reverse()+
  theme_void()

interaction_potential@meta.data %>%
  arrange(factor(sender_group, levels = c("rLN","DLBCL","FL"))) %>% ggplot() + 
  scattermore::geom_scattermore(mapping = aes_string(x = "UMAP_1", 
                                                     y = "UMAP_2", color = "sender_group"))+
  scale_color_manual(values = c("grey85", "#00A1E0","grey80"))+
  scale_x_reverse()+
  scale_y_reverse()+
  theme_void() ###color changed bechause it is to light

interaction_potential@meta.data %>%
  arrange(factor(sender_group, levels = c("FL","rLN","DLBCL"))) %>% ggplot() + 
  scattermore::geom_scattermore(mapping = aes_string(x = "UMAP_1", 
                                                     y = "UMAP_2", color = "sender_group"))+
  scale_color_manual(values = c("grey80", "grey80","#67B86E"))+
  scale_x_reverse()+
  scale_y_reverse()+
  theme_void()
```

## G
### left
```{r}
interaction_potential@meta.data$sender_group <- factor(interaction_potential@meta.data$sender_group, levels = c("DLBCL", "FL", "rLN"))

interaction_potential@meta.data <- mutate(interaction_potential@meta.data, zones_binned = case_when(zones == "other"~"Other",
                                                                                                    zones == "Inflammatory ngh"~"Inflammatory",
                                                                                                    zones == "B cell zone like ngh"~"B cell zone",
                                                                                                    zones == "T cell zone like ngh"~"T cell zone"))

interaction_potential@meta.data$zones_binned <- factor(interaction_potential@meta.data$zones_binned, levels = c("Other", "Inflammatory", "B cell zone", "T cell zone"))

p_zones <- interaction_potential@meta.data %>% 
  group_by(zones_binned,sender_group) %>% tally() %>% 
ggplot(aes(x = zones_binned, y = n, fill = sender_group)) + 
  geom_bar(stat = "identity", position = "fill", width = 0.5) + 
  theme_bw() + 
  theme(
    plot.title   = element_text(size = 12, color = "black"),
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = "black"), 
    aspect.ratio = 1.25,
    axis.text.y  = element_text(size = 12, color = "black"),
    axis.title.x = element_text(size = 12, color = "black"),
    axis.title.y = element_blank(), 
    axis.text.x  = element_text(size = 12, color = "black")
  ) + 
  scale_fill_manual(values = annotation_colors$Type_binned) +
  labs(y = "Fraction per zone") +
  coord_flip()
```

### right 
```{r}
interaction_potential$sender_new_v4 <- ifelse(interaction_potential$sender_Clusters_final %in% c("FDC", "med-FRC", "MRC/IFR", "PvC", "SMC", "TRC"), 
                                   "FRC", interaction_potential$sender_Clusters_final)
interaction_potential$reciver_new_v4 <- ifelse(interaction_potential$receiver_Clusters_final %in% c("FDC", "med-FRC", "MRC/IFR", "PvC", "SMC", "TRC"), 
                                   "FRC", interaction_potential$receiver_Clusters_final)
interaction_potential$sender_reciver_v4 <- paste0(interaction_potential$sender_new_v4, "_", interaction_potential$reciver_new_v4)

freq <- interaction_potential@meta.data %>% group_by(zones, sender_patient,sender_group) %>% 
  count(sender_reciver_v4) %>% ungroup() %>% group_by(sender_patient, sender_group) %>%     
  mutate(count=sum(n)) %>% ungroup() %>% filter(zones %in% c("Inflammatory ngh")) %>%
  dplyr::select(!zones) %>% group_by(sender_patient, sender_group, sender_reciver_v4, count) %>% summarise(sum_n=sum(n)) %>% 
  mutate(rel_count=sum_n/count) %>% ungroup() %>% group_by(sender_reciver_v4) %>% mutate(sum=sum(rel_count))
cutoff <- quantile(freq$sum, 8/10)
freq <- freq %>% filter(sum>0.30)

freq$sender_reciver_v4 <- sub("^LAF", "rFRC", freq$sender_reciver_v4)

freq$sender_group <- factor(freq$sender_group, levels = c("DLBCL", "FL", "rLN"))

p_infl <- ggplot(freq, aes(x=reorder(sender_reciver_v4, sum) , y=rel_count, fill=sender_group)) + 
  geom_bar(stat ="identity", width = 0.5) + 
  theme_bw() + 
  theme(
    plot.title   = element_text(size = 12, color = "black"),
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = "black"), 
    aspect.ratio = 1.25,
    axis.text.y  = element_text(size = 12, color = "black"),
    axis.title.x = element_text(size = 12, color = "black"),
    axis.title.y = element_blank(), 
    axis.text.x  = element_text(size = 12, color = "black")
  ) + 
  scale_fill_manual(values = annotation_colors$Type_binned) +
  labs(y = "Fraction per interaction") +
  scale_x_discrete(position = "top") +
  coord_flip()


p_zones + p_infl
```


# H - I
```{r}
scriabin <- read_excel("") %>% column_to_rownames(var = "...1") #source data for Figure 4H and I provided in the manuscript (Seurat module score across inflammatory (CXCL9/10/11=CXCR3) and homeostatic chemokine-receptor pairs (CXCL13=CXCR5, CXCL12=CXCR4, CCL19/21=CCR7) from Scriabin. 

Calculation (for reference):
#merged_obj <- AddModuleScore(merged_obj, features = list(c("CXCL13=CXCR5", "CXCL12=CXCR4", "CCL19=CCR7", "CCL21=CCR7"),
#                                                                 c("CXCL9=CXCR3" ,"CXCL10=CXCR3" , "CXCL11=CXCR3")), 
#                                 name = c("homeostatic", "ifn"), nbin = 2, ctrl = 20)
```
```{r}
dis_colors <- c("#67B86E", "#8BCDE0", "#8D60B5")
comparisons <- list(c("rLN", "DLBCL"), c("FL", "DLBCL"))
```

```{r}
p_h <- ggplot(scriabin, aes(x = sender_group, y = `Homeostatic chemokines and receptors`, fill = sender_group)) +
  geom_violin(scale = "width", trim = FALSE, width = 0.75) +
  geom_boxplot(inherit.aes = TRUE, width = 0.1, outlier.size = 0, alpha = 0.5, notch = FALSE) + 
  geom_hline(yintercept = mean(scriabin$`Homeostatic chemokines and receptors`), linetype = 2) + # Add horizontal line at base mean
  ggtitle("Homeo") + 
  scale_y_continuous(limits = c(-1, 4.5), 
                     breaks = c(-1,0,1,2,3,4)) +
  coord_flip()+
  theme(
    plot.title   = element_text(size = 12, color = "black"),
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = "black"), 
    aspect.ratio = 0.75,
    axis.text.y  = element_text(size = 12, color = "black"),
    axis.title.x = element_text(size = 12, color = "black"),
    #axis.title.y = element_text(size = 15, color = "black", vjust = 1), 
    axis.title.y = element_blank(), 
    axis.text.x  = element_text(size = 12, color = "black")
  ) + 
  labs(x = "", y = "Module Score") +
  stat_compare_means(
    method = "wilcox.test",
    p.adjust.method = "BH",
    label = "p.format",
    label.y = c(3.85, 4.2),
    comparisons = comparisons
  ) +
  scale_fill_manual(values = dis_colors)

p_i <- ggplot(scriabin, aes(x = sender_group, y = `Inflammatory chemokines and receptors`, fill = sender_group)) +
  geom_violin(scale = "width", trim = F, width = 0.75) +
  geom_boxplot(inherit.aes = TRUE, width = 0.1, outlier.size = 0, alpha = 0.5, notch = FALSE) + 
  geom_hline(yintercept = mean(scriabin$`Inflammatory chemokines and receptors`), linetype = 2) + # Add horizontal line at base mean
  ggtitle("Infl") + 
  scale_y_continuous(limits = c(-1, 4.5), 
                     breaks = c(-1,0,1,2,3,4)) +
  coord_flip()+
  theme(
    plot.title   = element_text(size = 12, color = "black"),
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = "black"), 
    aspect.ratio = 0.75,
    axis.text.y  = element_text(size = 12, color = "black"),
    axis.title.x = element_text(size = 12, color = "black"),
    #axis.title.y = element_text(size = 15, color = "black", vjust = 1), 
    axis.title.y = element_blank(), 
    axis.text.x  = element_text(size = 12, color = "black")
  ) + 
  labs(x = "", y = "Module Score") +
  stat_compare_means(
    method = "wilcox.test",
    p.adjust.method = "BH",
    label = "p.format",
    label.y = c(3.85, 4.2),
    comparisons = comparisons
  ) +
  scale_fill_manual(values = dis_colors)
```

# J

```{r}
diff_score <- read.csv("") #source data for Figure 4J provided in the manuscript: diffusion score = mean euclidean distances between cells in the PCA space

p_j <- ggplot(diff_score, aes(x = sender_group, y = rowmean_pca, fill = sender_group)) +
  geom_violin(scale = "width", trim = F, width = 0.75) +
  geom_boxplot(inherit.aes = TRUE, width = 0.1, outlier.size = 0, alpha = 0.5, notch = FALSE) + 
  geom_hline(yintercept = mean(scriabin$rowmean_pca), linetype = 2) + # Add horizontal line at base mean
  ggtitle("Diff") + 
  #scale_y_continuous(limits = c(0,30), 
  #                   breaks = c(0,10,20,30)) +
  scale_y_log10()+
  coord_flip()+
  theme(
    plot.title   = element_text(size = 12, color = "black"),
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = "black"), 
    aspect.ratio = 0.75,
    axis.text.y  = element_text(size = 12, color = "black"),
    axis.title.x = element_text(size = 12, color = "black"),
    #axis.title.y = element_text(size = 15, color = "black", vjust = 1), 
    axis.title.y = element_blank(), 
    axis.text.x  = element_text(size = 12, color = "black")
  ) + 
  labs(x = "", y = "Mean Euclidean distances") +
  stat_compare_means(
    method = "wilcox.test",
    p.adjust.method = "BH",
    label = "p.format",
    #label.y = c(26, 28),
    comparisons = comparisons
  ) +
  scale_fill_manual(values = dis_colors)
```

